version: '3.9'
services:
  
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: axlneo
      MYSQL_PASSWORD: ax!16Kwo
      MYSQL_ROOT_PASSWORD: ax!16Kwo
    volumes:
      - .dbdata:/var/libmysql
    ports:
      - 33066:3306   